//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadPuerta
    {
        public long idActividad { get; set; }
        public Nullable<long> idTipoActividad { get; set; }
        public Nullable<long> idActividadPatio { get; set; }
        public Nullable<long> idTipoUnidad { get; set; }
        public Nullable<long> idModoAsignacion { get; set; }
        public Nullable<long> idTarifa { get; set; }
        public Nullable<long> idPuerta { get; set; }
        public Nullable<long> idOperadorRegistro { get; set; }
        public Nullable<long> idUnidad { get; set; }
        public Nullable<long> idTransportista { get; set; }
        public string codigoQR { get; set; }
        public string codigoBarras { get; set; }
        public string nota { get; set; }
        public string clave { get; set; }
        public Nullable<System.DateTime> fechaActividad { get; set; }
        public Nullable<long> idInspector { get; set; }
        public Nullable<System.DateTime> fechaInspeccion { get; set; }
        public string booking { get; set; }
        public Nullable<long> cargoA { get; set; }
        public Nullable<long> idCompaniaOperadora { get; set; }
        public Nullable<long> idLugarInicio { get; set; }
        public Nullable<long> idLugarDestino { get; set; }
        public Nullable<long> idOperadora_conductor { get; set; }
        public string numPlaca { get; set; }
        public string numLicencia { get; set; }
        public Nullable<long> idCompania { get; set; }
        public string condicionUnidad { get; set; }
        public Nullable<decimal> costoNormal { get; set; }
        public Nullable<decimal> porcentajeDescuento { get; set; }
        public string numAprobacion { get; set; }
        public Nullable<long> idImpuestosAplicables { get; set; }
        public Nullable<decimal> montoImpuestos { get; set; }
        public Nullable<long> idMoneda { get; set; }
        public string numUnidadAlterna { get; set; }
        public Nullable<bool> enviarEDI { get; set; }
        public string propietarioPatio { get; set; }
        public string arrendatarioPatio { get; set; }
        public Nullable<decimal> totalFactura { get; set; }
        public string numEDI { get; set; }
        public bool esVisible { get; set; }
        public long idEstatus { get; set; }
        public Nullable<bool> bolExtendido { get; set; }
        public Nullable<long> valor1 { get; set; }
        public string valor2 { get; set; }
        public string valor3 { get; set; }
        public string valor4 { get; set; }
        public string valor5 { get; set; }
        public Nullable<long> clave1 { get; set; }
        public Nullable<long> clave2 { get; set; }
        public Nullable<long> clave3 { get; set; }
        public Nullable<long> clave4 { get; set; }
        public Nullable<long> clave5 { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
        public string rutaBoleto { get; set; }
    }
}
