//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadInstantanea
    {
        public long idInstantanea { get; set; }
        public Nullable<long> idCamara { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<long> idActividadPuerta { get; set; }
        public Nullable<long> idActividadPatio { get; set; }
        public bool esVisible { get; set; }
        public long idEstatus { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
    }
}
