//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajones
    {
        public long idCajon { get; set; }
        public string nombreVisible { get; set; }
        public Nullable<long> numCajon { get; set; }
        public Nullable<long> idNivel { get; set; }
        public Nullable<long> idEstatus { get; set; }
        public Nullable<long> valorAsociado1 { get; set; }
        public Nullable<long> valorAsociado2 { get; set; }
        public string claveTexto { get; set; }
        public bool esVisible { get; set; }
        public bool esActivo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public long usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> usuarioModificacion { get; set; }
        public Nullable<int> ordenVisual { get; set; }
    }
}
