//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosElementos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosElementos()
        {
            this.CatalogosElementosExt = new HashSet<CatalogosElementosExt>();
        }
    
        public long idElemento { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public long idCatalogo { get; set; }
        public string nombre { get; set; }
        public string nombreVisible { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> valorAsociado { get; set; }
        public string claveTexto { get; set; }
        public bool esVisible { get; set; }
        public bool esActivo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public long usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> usuarioModificacion { get; set; }
        public Nullable<int> ordenVisual { get; set; }
        public bool esEditable { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosElementosExt> CatalogosElementosExt { get; set; }
    }
}
