//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogos()
        {
            this.CatalogosElementos = new HashSet<CatalogosElementos>();
        }
    
        public long idCatalogo { get; set; }
        public string nomCatalogo { get; set; }
        public string nomVisible { get; set; }
        public string txtDescripcion { get; set; }
        public string tipoDato { get; set; }
        public Nullable<long> valorAsociado { get; set; }
        public string claveTexto { get; set; }
        public bool esVisible { get; set; }
        public bool esActivo { get; set; }
        public bool esJerarquico { get; set; }
        public bool esExtendido { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public long usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> usuarioModificacion { get; set; }
        public Nullable<long> idEmpresa { get; set; }
        public bool esEditable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosElementos> CatalogosElementos { get; set; }
    }
}
