//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configInterfaz1
    {
        public long id { get; set; }
        public string idVentana { get; set; }
        public string nomComponente { get; set; }
        public string tipoDato { get; set; }
        public string origenDato { get; set; }
        public string nombreFuente { get; set; }
        public string valorInicial { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<bool> mostrarComponente { get; set; }
        public string etiquetaVisible { get; set; }
        public bool campoObligatorio { get; set; }
        public string tipoComponente { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
        public bool esVisible { get; set; }
        public long idEstatus { get; set; }
    }
}
