//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_errores1
    {
        public long id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Level { get; set; }
        public string logger { get; set; }
        public string Message { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Exception { get; set; }
        public string StackTrace { get; set; }
    }
}
