//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CDLogisticaAEntities : DbContext
    {
        public CDLogisticaAEntities()
            : base("name=CDLogisticaAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Aplicaciones> Aplicaciones { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Catalogos> Catalogos { get; set; }
        public virtual DbSet<CatalogosElementos> CatalogosElementos { get; set; }
        public virtual DbSet<CatalogosElementosExt> CatalogosElementosExt { get; set; }
        public virtual DbSet<configInterfaz> configInterfaz { get; set; }
        public virtual DbSet<LOG_bitacoraGeneral> LOG_bitacoraGeneral { get; set; }
        public virtual DbSet<LOG_bitacoraSesiones> LOG_bitacoraSesiones { get; set; }
        public virtual DbSet<LOG_Errores> LOG_Errores { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<ActividadAdjuntos> ActividadAdjuntos { get; set; }
        public virtual DbSet<ActividadInstantanea> ActividadInstantanea { get; set; }
        public virtual DbSet<ActividadPatio> ActividadPatio { get; set; }
        public virtual DbSet<ActividadPuerta> ActividadPuerta { get; set; }
        public virtual DbSet<ActividadVideo> ActividadVideo { get; set; }
        public virtual DbSet<Cajones> Cajones { get; set; }
        public virtual DbSet<Camaras> Camaras { get; set; }
        public virtual DbSet<configInterfaz1> configInterfaz1 { get; set; }
        public virtual DbSet<LOG_errores1> LOG_errores1 { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<Patios> Patios { get; set; }
        public virtual DbSet<PersonasFisicas> PersonasFisicas { get; set; }
        public virtual DbSet<PersonasMorales> PersonasMorales { get; set; }
        public virtual DbSet<Puertas> Puertas { get; set; }
        public virtual DbSet<Sectores> Sectores { get; set; }
        public virtual DbSet<Tarifas> Tarifas { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<vwActividadesPuerta> vwActividadesPuerta { get; set; }
        public virtual DbSet<vwPatiosCajones_status> vwPatiosCajones_status { get; set; }
    
        public virtual ObjectResult<spCatalogoElementos_ObtenerListadoSimple_Result> spCatalogoElementos_ObtenerListadoSimple(string nombreCatalogo)
        {
            var nombreCatalogoParameter = nombreCatalogo != null ?
                new ObjectParameter("NombreCatalogo", nombreCatalogo) :
                new ObjectParameter("NombreCatalogo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatalogoElementos_ObtenerListadoSimple_Result>("spCatalogoElementos_ObtenerListadoSimple", nombreCatalogoParameter);
        }
    
        public virtual ObjectResult<spCamaras_ObtenerListadoSimple_Result> spCamaras_ObtenerListadoSimple(Nullable<long> idPuerta)
        {
            var idPuertaParameter = idPuerta.HasValue ?
                new ObjectParameter("IdPuerta", idPuerta) :
                new ObjectParameter("IdPuerta", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCamaras_ObtenerListadoSimple_Result>("spCamaras_ObtenerListadoSimple", idPuertaParameter);
        }
    
        public virtual ObjectResult<spPuertas_ObtenerListadoSimple_Result> spPuertas_ObtenerListadoSimple(Nullable<long> idPatio, Nullable<long> idSector, Nullable<long> idNivel)
        {
            var idPatioParameter = idPatio.HasValue ?
                new ObjectParameter("IdPatio", idPatio) :
                new ObjectParameter("IdPatio", typeof(long));
    
            var idSectorParameter = idSector.HasValue ?
                new ObjectParameter("IdSector", idSector) :
                new ObjectParameter("IdSector", typeof(long));
    
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("IdNivel", idNivel) :
                new ObjectParameter("IdNivel", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPuertas_ObtenerListadoSimple_Result>("spPuertas_ObtenerListadoSimple", idPatioParameter, idSectorParameter, idNivelParameter);
        }
    
        public virtual ObjectResult<spNiveles_DisponibilidadCajonesListadoSimple_Result> spNiveles_DisponibilidadCajonesListadoSimple(Nullable<long> idNivel)
        {
            var idNivelParameter = idNivel.HasValue ?
                new ObjectParameter("IdNivel", idNivel) :
                new ObjectParameter("IdNivel", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNiveles_DisponibilidadCajonesListadoSimple_Result>("spNiveles_DisponibilidadCajonesListadoSimple", idNivelParameter);
        }
    
        public virtual ObjectResult<spPatios_DisponibilidadSectores_Result> spPatios_DisponibilidadSectores(Nullable<long> idPatio)
        {
            var idPatioParameter = idPatio.HasValue ?
                new ObjectParameter("IdPatio", idPatio) :
                new ObjectParameter("IdPatio", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPatios_DisponibilidadSectores_Result>("spPatios_DisponibilidadSectores", idPatioParameter);
        }
    
        public virtual ObjectResult<spSectores_DisponibilidadNiveles_Result> spSectores_DisponibilidadNiveles(Nullable<long> idSector)
        {
            var idSectorParameter = idSector.HasValue ?
                new ObjectParameter("IdSector", idSector) :
                new ObjectParameter("IdSector", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSectores_DisponibilidadNiveles_Result>("spSectores_DisponibilidadNiveles", idSectorParameter);
        }
    
        public virtual ObjectResult<spNiveles_DisponibilidadCajonesListadoHTML_Result> spNiveles_DisponibilidadCajonesListadoHTML(Nullable<long> idSector)
        {
            var idSectorParameter = idSector.HasValue ?
                new ObjectParameter("IdSector", idSector) :
                new ObjectParameter("IdSector", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNiveles_DisponibilidadCajonesListadoHTML_Result>("spNiveles_DisponibilidadCajonesListadoHTML", idSectorParameter);
        }
    
        public virtual ObjectResult<spSectores_DisponibilidadNivelesListadoHTML_Result> spSectores_DisponibilidadNivelesListadoHTML(Nullable<long> idPatio)
        {
            var idPatioParameter = idPatio.HasValue ?
                new ObjectParameter("IdPatio", idPatio) :
                new ObjectParameter("IdPatio", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSectores_DisponibilidadNivelesListadoHTML_Result>("spSectores_DisponibilidadNivelesListadoHTML", idPatioParameter);
        }
    
        public virtual ObjectResult<spPatios_DisponibilidadSectoresListadoHTML_Result> spPatios_DisponibilidadSectoresListadoHTML(Nullable<long> idPatio)
        {
            var idPatioParameter = idPatio.HasValue ?
                new ObjectParameter("IdPatio", idPatio) :
                new ObjectParameter("IdPatio", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPatios_DisponibilidadSectoresListadoHTML_Result>("spPatios_DisponibilidadSectoresListadoHTML", idPatioParameter);
        }
    
        public virtual ObjectResult<spPuertas_ObtenerReporteGeneral_Result> spPuertas_ObtenerReporteGeneral(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPuertas_ObtenerReporteGeneral_Result>("spPuertas_ObtenerReporteGeneral", tipoParameter);
        }
    }
}
