//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public long idParametro { get; set; }
        public Nullable<long> idModulo { get; set; }
        public string nomParametro { get; set; }
        public string descripcion { get; set; }
        public string tipoDato { get; set; }
        public string rangoValorSerie { get; set; }
        public string valor1 { get; set; }
        public string valor2 { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
        public bool esVisible { get; set; }
        public int numClasificador { get; set; }
        public string txtClasificador { get; set; }
        public Nullable<int> numClasificador2 { get; set; }
        public bool esActivo { get; set; }
    }
}
