//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasMorales
    {
        public long idPersonaMoral { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string direccion { get; set; }
        public string paginaweb { get; set; }
        public string contacto { get; set; }
        public string comentarios { get; set; }
        public Nullable<long> idNivelSuperior { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<bool> esCliente { get; set; }
        public Nullable<bool> esProveedor { get; set; }
        public Nullable<long> idEmpresa { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
        public bool esVisible { get; set; }
        public long idEstatus { get; set; }
    }
}
