//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifas
    {
        public long idTarifa { get; set; }
        public Nullable<long> idTipo1 { get; set; }
        public string nomTarifa { get; set; }
        public Nullable<long> idMoneda { get; set; }
        public Nullable<decimal> valorAsociado1 { get; set; }
        public Nullable<decimal> valorAsociado2 { get; set; }
        public Nullable<decimal> valorAsociado3 { get; set; }
        public Nullable<decimal> valorAsociado4 { get; set; }
        public Nullable<long> idTipo2 { get; set; }
        public Nullable<long> idEmpresa { get; set; }
        public Nullable<long> idClasificador1 { get; set; }
        public Nullable<long> idClasificador2 { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public Nullable<long> idEstatus { get; set; }
        public Nullable<bool> esVigente { get; set; }
        public Nullable<int> ordenVisual { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
    }
}
