//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades
    {
        public long idUnidad { get; set; }
        public Nullable<long> idTipo3 { get; set; }
        public string nomUnidad { get; set; }
        public Nullable<long> numUnidad { get; set; }
        public string clasificador1 { get; set; }
        public string clasificador2 { get; set; }
        public Nullable<long> idTipo2 { get; set; }
        public Nullable<long> idPropietario { get; set; }
        public Nullable<long> idArrendador { get; set; }
        public string valorAsociado1 { get; set; }
        public string CeCo { get; set; }
        public Nullable<long> idEstatusUnidad { get; set; }
        public string modelo { get; set; }
        public Nullable<System.DateTime> fechaInicialServicio { get; set; }
        public Nullable<long> idUbicacionFisica { get; set; }
        public Nullable<decimal> montoLimiteReparacion { get; set; }
        public Nullable<long> idTipo1 { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioRegistro { get; set; }
        public Nullable<long> idUsuarioModificacion { get; set; }
        public bool esVisible { get; set; }
        public long idEstatus { get; set; }
    }
}
