//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public long id { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Source { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<long> usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> usuarioModificacion { get; set; }
        public short esActivo { get; set; }
        public Nullable<System.DateTime> LastDirectoryUpdate { get; set; }
    }
}
