//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPatiosCajones_status
    {
        public long idPatio { get; set; }
        public string clavePatio { get; set; }
        public long estatusPatio { get; set; }
        public Nullable<long> idPropietario { get; set; }
        public long idSector { get; set; }
        public string claveSector { get; set; }
        public long estatusSector { get; set; }
        public long idNivel { get; set; }
        public string claveNivel { get; set; }
        public long estatusNivel { get; set; }
        public Nullable<int> numCajones { get; set; }
        public string claveCajon { get; set; }
        public string nombreVisible { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCajon { get; set; }
        public Nullable<long> estatusCajon { get; set; }
        public Nullable<long> numCajon { get; set; }
        public Nullable<long> valorAsociado1 { get; set; }
        public Nullable<long> valorAsociado2 { get; set; }
        public string nomEstatusCajon { get; set; }
        public string nomVisibleEstatusCajon { get; set; }
    }
}
